### ISSUE TITLE
Hello,there is a bug

### ISSUE THREAD

**Issue by lokisama** [anywhichway/stringformatter#11]
Dear Author,
I found a bug like that. You try ?
Should be 'Apr', but now 'AMpr'.
Thank you.

var t = StringFormatter.format("{Date: {format: 'DD-MMM-YYYY hh:mm:ss:SSS A'}}",new Date('2015-04-12 00:12:23'));

**Comment by anywhichway** [comment]
We have identified the source of the bug and expect to deploy a fix within 48 hours.

**Comment by anywhichway** [comment]
fixed and deployed as v0.0.82
