### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by VaclavElias** [anywhichway/stringformatter#7]
Please, add a table (or any form) of all possible important examples to your wiki. It will make it very easy to see in glance what we can get from this library just in seconds :)

**Comment by anywhichway** [comment]
Will do within the next week. Thanks for the suggestion!

**Comment by anywhichway** [comment]
95% of usage is now covered in an Examples section.

**Comment by VaclavElias** [comment]
Thank you, this was super quick response and action and now very easy to
see what I can get if I am looking for a particular string format :)
